name: Upload to Release

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release (if not exists)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: data-raw/infosiga_*.parquet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
